### ISSUE TITLE
Callback URL mismatch.

### ISSUE THREAD

**Issue by bmcculley** [mozilla/mentoring#181]
When trying to visit the url https://mentoring.mozilla.com/ I get redirected to https://auth.mozilla.auth0.com and receive the following error:

Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.
Please go to the Application Settings page and make sure you are sending a valid callback url from your application.

**Comment by djmitche** [comment]
Yeah, it's not correctly deployed yet.  This is being tracked internally.  Thanks for looking though!
