### ISSUE TITLE
Support local development

### ISSUE THREAD

**Issue by djmitche** [mozilla/mentoring#36]
Let's make local development (much) easier, following the typical Django development process

* Allow running with a local DB
* Allow running with a DB-based sign-in so we don't require auth0 (can we leverage the admin sign-in form for this?). 
* Explain how to build the frontend

**Comment by jwhitlock** [comment]
For [Tecken](https://github.com/mozilla-services/tecken) we used [docker-compose](https://github.com/mozilla-services/tecken/blob/main/docker-compose.yml) and the [mozilla/oidc-testprovider image](https://hub.docker.com/r/mozilla/oidc-testprovider) from [mozilla/docker-test-mozilla-django-oidc](https://github.com/mozilla/docker-test-mozilla-django-oidc), with some [additions](https://github.com/mozilla-services/tecken/tree/main/docker/images/oidcprovider) to add test users to the OIDC database. You'd have a [dev-only configuration](https://tecken.readthedocs.io/en/latest/configuration.html#authentication) that would redirect to http://oidc.127.0.0.1.nip.io:8081/ for login (https://nip.io is a neat service), then back to Tecken dev. It felt like duct tape and wire, but it mostly worked.

**Comment by djmitche** [comment]
I think I can figure a way to run with local-only stuff for development, so there's no need for the OIDC in dev.  I want to make sure I do it in a failsafe way so that we don't "accidentally" allow local logins when this goes to production.  So development will probably be something like

```
MODE=development python3 manage.py runserver
```
where if MODE isn't set then it assumes it's running in a deployment environment.

**Comment by jwhitlock** [comment]
That will work. This sounds similar to the strategy of django-configurations - https://django-configurations.readthedocs.io/en/stable/

**Comment by djmitche** [comment]
oo, thanks for that pointer!
