### ISSUE TITLE
makemigrations fails

### ISSUE THREAD

**Issue by djmitche** [mozilla/mentoring#42]
> I'm getting an error ``ValueError: Cannot serialize function: lambda`` when I run ``python3 manage.py makemigrations``. It looks like it is the ``lambda`` used for the default in ``Pair.start_date``, which was added before this PR. I'm OK fixing it in this or a future PR.
> 
> One way to fix it is to use [``auto_now_add=True``](https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.DateField.auto_now_add) instead of ``default``. This has some repercusions as mentioned in the docs (sets ``editable=False`` and ``blank=True``, which may prevent you from  creating a ``Pair`` with a date in the past in the Django admin).
> 
> The other way is to set ``default=timezone.now``, with a ``from django.utils import timezone``. This uses the ``TIME_ZONE`` setting, set to the default of ``UTC``.

_Originally posted by @jwhitlock in https://github.com/mozilla/mentoring/pull/40#discussion_r562266859_

**Comment by djmitche** [comment]
Maybe we should add `makemigrations` to CI, and assert that it succeeds and does not make any changes.

**Comment by djmitche** [comment]
Thanks @jwhitlock for the detailed suggestions -- `timezone.now` looks like the right fix here.

**Comment by jwhitlock** [comment]
I think ``sandbox/bin/python3 manage.py makemigrations --dry-run --check`` would work as a CI check
